name: CppCheck

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release

jobs:
  cppcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Install Packages
      run: sudo apt update; sudo apt install -y lua5.4 cppcheck libmnl-dev liblua5.4-dev cmake ninja-build

    - name: cppcheck
      run: cppcheck --enable=all --suppressions-list=CppCheckSuppressions.txt src/*.c
